FROM ubuntu:16.04

ENV API_URL=http://localhost:8000

COPY frontend-example-docker .

RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get install -y nodejs && \
    npm install && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/* && \
    useradd -m app_user && \
    mkdir dist && \
    chown app_user dist

USER app_user

EXPOSE 5000

CMD npm start
