version: '3'

services:
  ex_2.3_front:
    container_name: ex_2.3_front
    build:
      context: ../../Part1/1.12
      dockerfile: ../../Part1/1.12/Dockerfile.frontend
    ports:
      - 5000:5000

  ex_2.3_back:
    container_name: ex_2.3_back
    build:
      context: ../../Part1/1.12
      dockerfile: ../../Part1/1.12/Dockerfile.backend
    ports:
      - 8000:8000
