version: '3.5'

services:
  ex_2.9_front:
    container_name: ex_2.9_front
    build:
      context: ../../Part1/1.12
      dockerfile: ../../Part1/1.12/Dockerfile.frontend
    environment:
      - API_URL=/api/
    ports:
      - 5000:5000

  ex_2.9_back:
    container_name: ex_2.9_back
    build:
      context: ../../Part1/1.12
      dockerfile: ../../Part1/1.12/Dockerfile.backend
    environment:
      - REDIS=ex_2.9_redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=ex_2.9_postgres
    ports:
      - 8000:8000

  ex_2.9_redis:
    container_name: ex_2.9_redis
    image: redis

  ex_2.9_postgres:
    container_name: ex_2.9_postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database:/var/lib/postgresql/data

  ex_2.9_nginx:
    container_name: ex_2.9_nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80


