version: '3'

services:
  ex_2.5_front:
    container_name: ex_2.5_front
    build:
      context: ../../Part1/1.12
      dockerfile: ../../Part1/1.12/Dockerfile.frontend
    ports:
      - 5000:5000

  ex_2.5_back:
    container_name: ex_2.5_back
    build:
      context: ../../Part1/1.12
      dockerfile: ../../Part1/1.12/Dockerfile.backend
    environment:
      - REDIS=ex_2.5_redis
    ports:
      - 8000:8000

  ex_2.5_redis:
    container_name: ex_2.5_redis
    image: redis
