# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Login to heorku registry
    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 
      run: heroku container:login

    # Builds the project using Dockerfile and pushes to heroku registry
    - name: Build and push
      working-directory: Part3/3.2
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 
      run: heroku container:push -a chanioxaris-mooc-workflow web
        
    # Release app   
    - name: Release
      working-directory: Part3/3.2 
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 
      run: heroku container:release -a chanioxaris-mooc-workflow web
